### ISSUE TITLE
run_epoch tqdm

### ISSUE THREAD

**Issue by EmreOzkose** [JuanFMontesinos/flerken#10]
Hi,

I think there is a problem [here](https://github.com/JuanFMontesinos/flerken/blob/4a4ce5f669f7566757bc5a8951ea19fa5ef1caf1/flerken/framework/pytorchframework.py#L511). tqdm counts epoch, but should count batches?

**Comment by JuanFMontesinos** [comment]
Hi,
The counter shows both iterations and epochs. So for example
![imagen](https://user-images.githubusercontent.com/32466310/145428333-111df610-5290-4fb6-85da-808266135acd.png)
the loading bar shows iterations per epoch meanwhile the counter shows epochs.

**Comment by EmreOzkose** [comment]
I see now. Both epoch and train iteration are 2000. Thank you.
